# Generated by Django 2.2.8 on 2023-06-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20230621_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='recruits',
            field=models.ManyToManyField(blank=True, null=True, to='recruit.Recruit'),
        ),
    ]
